language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 5.6
      env: SYMFONY_VERSION='3.0.*'

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

